---
# file: roles/workstation-common/tasks/cups.yml

- name: be sure cups is installed
  dnf: name=cups state=installed
  tags:
   - install
   - cups
   - print
 
- name: be sure cups and cups-browsed are enabled
  systemd: name={{item}} enabled=yes
  with_items:
   - cups
   - cups-browsed
  tags:
   - install
   - atomic
   - cups
   - print

- name: be sure cups and cups-browsed are running
  systemd: name={{item}} state=running
  ignore_errors: yes 
  with_items:
   - cups
   - cups-browsed
  tags:
   - install
   - atomic
   - cups
   - print

