# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1363937355);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 225280);
user_pref("browser.migration.version", 8);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage", "file:///netshare/networld/usershare/world/junior_web/index.html");
user_pref("browser.startup.homepage_override.buildID", "20130311161054");
user_pref("browser.startup.homepage_override.mstone", "19.0.2");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":4}");
user_pref("dwhelper.conv-conf.auto.bc1e2619f37bea59f347c7c0c775df02", true);
user_pref("dwhelper.convert-free", false);
user_pref("dwhelper.last-media-host-blacklist", "pop6.com|redlightcenter.com|dtiserv.com|mp3tunes.com|netflix.com");
user_pref("dwhelper.last-shared-blacklist", "1363937486517");
user_pref("dwhelper.last-version", "4.9.10");
user_pref("dwhelper.menu-expiration", 60);
user_pref("dwhelper.scap.file-ext", "ogv");
user_pref("dwhelper.scap.start-args", "--overwrite -x {x} -y {y} --width {width} --height {height} --on-the-fly-encoding -o {file}");
user_pref("dwhelper.scap.start-pgm", "/usr/bin/recordmydesktop");
user_pref("dwhelper.scap.stop-args", "-3 recordmydesktop");
user_pref("dwhelper.scap.stop-pgm", "/usr/bin/killall");
user_pref("dwhelper.smartnamer.last-shared", 1363937537);
user_pref("extensions.adblockplus.currentVersion", "2.2.3");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"version\":\"2.2.3\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7Bb9db16a4-6edc-47ec-a1f4-b86292ed211d%7D:4.9.10,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:19.0.2");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"{b9db16a4-6edc-47ec-a1f4-b86292ed211d}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{b9db16a4-6edc-47ec-a1f4-b86292ed211d}\",\"mtime\":1359132291000},\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\",\"mtime\":1361977464000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1363362021000}}}]");
user_pref("extensions.lastAppVersion", "19.0.2");
user_pref("extensions.lastPlatformVersion", "19.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20130311161054");
user_pref("gecko.mstone", "19.0.2");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 12428);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1363937542);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1366529487);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
